# download & install python!
FROM python:3.8-slim

# copy the code in the desired directory. (WORKDIR, COPY)
WORKDIR /usr/src/app

COPY . .



# Install requiements.


# CMD: python   app.py
CMD ["python", "./app.py"]
